const fs = require("fs");
const path = require("path");
const { TextDecoder } = require("util");

const rootDir = path.resolve(__dirname, "..");
const databaseDir = path.resolve(rootDir, "../../docs/database");
const outputPath = path.join(rootDir, "Script/item_data_static.lua");

const sources = [
  {
    file: "物品.csv",
    sourceType: "物品",
    idColumns: ["/Objects", "Objects", "ID", "id"],
    mapping: {
      internalName: ["EName"],
      weight: ["Weight"],
      iconId: ["IconID"],
      level: ["Level"],
      name: ["Name"],
      description: ["Description"],
      characteristic: ["Characteristic//包含了所有特性", "Characteristic"],
      tag: ["Tag"],
      price: ["Price"],
    },
  },
  {
    file: "食物.csv",
    sourceType: "食物",
    idColumns: ["/Food", "Food", "ID", "id"],
    mapping: {
      name: ["Name"],
      weight: ["Weight"],
      iconId: ["IconID"],
      price: ["Price"],
      level: ["Level"],
      description: ["Description"],
      characteristic: ["Characteristic"],
      tag: ["Tag"],
    },
  },
  {
    file: "装备.csv",
    sourceType: "装备",
    idColumns: ["/Equip", "Equip", "ID", "id"],
    mapping: {
      internalName: ["Type"],
      name: ["Name"],
      iconId: ["IconID"],
      description: ["Description"],
      level: ["Level"],
      price: ["Price"],
      weight: ["Weight"],
      buffId: ["BuffID"],
      func: ["Func"],
      funcPlus: ["FuncPlus"],
      needSource: ["NeedSource"],
      attackRange: ["AttackRange"],
    },
  },
  {
    file: "配件.csv",
    sourceType: "配件",
    idColumns: ["ID", "/Parts", "Parts", "id"],
    mapping: {
      name: ["Name"],
      description: ["Description"],
      level: ["Level"],
      price: ["Price"],
      buffId: ["BuffID"],
      weight: ["Weight"],
      iconId: ["IconID"],
      needSource: ["NeedSource"],
    },
  },
];

function decodeFile(filePath) {
  const bytes = fs.readFileSync(filePath);
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch (error) {
    return new TextDecoder("gb18030").decode(bytes);
  }
}

function stripBom(text) {
  return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const next = text[i + 1];

    if (inQuotes) {
      if (ch === '"' && next === '"') {
        cell += '"';
        i++;
      } else if (ch === '"') {
        inQuotes = false;
      } else {
        cell += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      row.push(cell);
      cell = "";
    } else if (ch === "\n") {
      row.push(cell.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      cell = "";
    } else {
      cell += ch;
    }
  }

  if (cell.length > 0 || row.length > 0) {
    row.push(cell.replace(/\r$/, ""));
    rows.push(row);
  }

  return rows.filter((current) => current.some((value) => value !== ""));
}

function normalizeHeader(header) {
  return stripBom(header || "").trim();
}

function getFirst(row, headers, names) {
  for (const name of names) {
    const index = headers.indexOf(name);
    if (index !== -1 && row[index] !== undefined && row[index] !== "") {
      return row[index];
    }
  }
  return "";
}

function rowToRecord(row, headers, source) {
  const record = {
    id: getFirst(row, headers, source.idColumns),
    sourceType: source.sourceType,
    sourceOrigin: "static",
    name: "",
    internalName: "",
    level: "",
    weight: "",
    price: "",
    iconId: "",
    description: "",
    tag: "",
    characteristic: "",
    buffId: "",
    func: "",
    funcPlus: "",
    needSource: "",
    attackRange: "",
  };

  for (const [target, sourceColumns] of Object.entries(source.mapping)) {
    record[target] = getFirst(row, headers, sourceColumns);
  }

  return record;
}

function escapeLuaString(value) {
  return String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/"/g, '\\"');
}

function emitLua(records) {
  const lines = [
    "-- Auto-generated by tools/generate_static_data.js. Do not edit by hand.",
    "return {",
  ];

  for (const record of records) {
    lines.push("    {");
    for (const key of [
      "id",
      "name",
      "internalName",
      "sourceType",
      "sourceOrigin",
      "level",
      "weight",
      "price",
      "iconId",
      "description",
      "tag",
      "characteristic",
      "buffId",
      "func",
      "funcPlus",
      "needSource",
      "attackRange",
    ]) {
      lines.push(`        ${key} = "${escapeLuaString(record[key])}",`);
    }
    lines.push("    },");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

const records = [];
for (const source of sources) {
  const filePath = path.join(databaseDir, source.file);
  const text = stripBom(decodeFile(filePath));
  const rows = parseCsv(text);
  const headers = rows[0].map(normalizeHeader);

  for (const row of rows.slice(1)) {
    const record = rowToRecord(row, headers, source);
    if (record.id && record.name) {
      records.push(record);
    }
  }
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, emitLua(records), "utf8");
console.log(`Generated ${records.length} records at ${path.relative(process.cwd(), outputPath)}`);
